global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'gemini'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/metrics/gemini'
    scheme: 'http'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'gemini_.*'
        action: keep 